name: PR build
on: [pull_request]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust Stable
        run: rustup update stable && rustup default stable

      - name: Check the code formatting with rustfmt
        run: cargo fmt --all -- --check

      - name: Ensure there are no warnings with Clippy
        run: cargo clippy --all -- -Dwarnings

      - name: Check if the configuration is correct
        run: |
          cargo run --bin crater -- create-lists
          cargo run --bin crater -- check-config

  test:
    name: Linux testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust Stable
        run: rustup update stable && rustup default stable

      - name: Build Crater
        run: cargo build

      - name: Run Crater tests
        run: |
          cargo run --bin crater -- create-lists
          cargo build --bin jobserver
          sudo cp target/debug/jobserver /usr/local/bin/jobserver-crater-fwd
          cargo test
